Update credits section on github page
wlsf82/protractor-helper pull request #118
Opened 2021-01-15 19:34 UTC by pedrohyvo

Now, README and github page are accurate. Closes #117

## Pull Request Checklist

- [x] Have you followed the steps in our [Contributing](https://github.com/wlsf82/protractor-helper/blob/master/docs/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/wlsf82/protractor-helper/pulls) for the same update/change?
- [x] Have you successfully ran tests with your changes locally?
- [x] Have you written new tests for your changes, if necessary?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you made improvements to the documentation, if necessary? ([docs/](https://github.com/wlsf82/protractor-helper/tree/master/docs) folder and [README.md](https://github.com/wlsf82/protractor-helper/blob/master/README.md))
- [x] Have you linked the correct [GitHub issue](https://github.com/wlsf82/protractor-helper/issues), if there is any?

> Pull requests that do not pass the coding static analysis and the automated tests on [Github Actions](https://github.com/wlsf82/protractor-helper/actions), and the code quality verification on [Better Code Hub](https://bettercodehub.com/) will not be reviewed.

2021-01-15 21:27 UTC, wlsf82 requested changes
@pedrohyvo, it seems that your PR is behind master by one commit.
Can you rebase it based on the original repository so that only the `index.md` file will be changed?

2021-01-15 21:42 UTC, pedrohyvo commented
@wlsf82 now it's ready to go 🚀

2021-01-15 22:03 UTC, wlsf82 commented on index.md
> +---
```suggestion
---
```

2021-01-15 22:03 UTC, wlsf82 commented on index.md
> +---
Oops, it seems that you add a space by mistake.

2021-01-15 22:07 UTC, wlsf82 requested changes
Nitpick.

2021-01-15 22:10 UTC, wlsf82 commented on index.md
> +---
Or is it on purpose? Since the line looks thicker here https://github.com/pedrohyvo/protractor-helper/blob/master/index.md

2021-01-18 14:33 UTC, wlsf82 approved these changes
Thanks for another contribution, @pedrohyvo! 👊🏻

2021-01-18 14:35 UTC, PauloGoncalvesBH commented on index.md
> +Thanks to [Paulo Gonçalves](https://www.linkedin.com/in/paulo-goncalves/), [Lucas Amaral](https://www.linkedin.com/in/lopesdoamaral/), [Michiel Cuijpers](https://github.com/MichielCuijpers), [Ghazi K
```suggestion
Thanks to [Paulo Gonçalves](https://www.linkedin.com/in/paulo-goncalves/), [Lucas Amaral](https://www.linkedin.com/in/lopesdoamaral/), [Ghazi Khan](https://codewithghazi.com/), and [Pedro Hyvo](https://www.linkedin.com/in/pedrohyvo/) for contributing to the project.
```

@wlsf82 será necessário a inclusão do Michiel Cuijpers? Sua contribuição foi a inclusão do badge do Better Code Hub, que ele tem alguma ligação direta.

https://github.com/wlsf82/protractor-helper/commits?author=MichielCuijpers

2021-01-18 14:36 UTC, wlsf82 commented on index.md
> +Thanks to [Paulo Gonçalves](https://www.linkedin.com/in/paulo-goncalves/), [Lucas Amaral](https://www.linkedin.com/in/lopesdoamaral/), [Michiel Cuijpers](https://github.com/MichielCuijpers), [Ghazi K
Toda contribuição é contribuição @PauloGoncalvesBH, não vejo porquê excluí-lo.

2021-01-18 14:36 UTC, wlsf82 requested changes
@pedrohyvo, it seems that your branch is behind the main repo again. Besides this PR commits, I also see the one from a previous PR, where you added the MIT license badge. Can you rebase it, please?

2021-01-18 17:58 UTC, pedrohyvo commented
> @pedrohyvo, it seems that your branch is behind the main repo again. Besides this PR commits, I also see the one from a previous PR, where you added the MIT license badge. Can you rebase it, please?

Removed @wlsf82

2021-01-18 18:00 UTC, PauloGoncalvesBH approved these changes

2021-01-18 19:21 UTC, wlsf82 requested changes
@pedrohyvo (and @PauloGoncalvesBH), your PR should be changing only the `index.md` file, but instead, it's also changing the `README.md` and `docs/PT-BR/README.md` files.

I suggest that you reset your branch based on the `master` branch of the main repo and then add only the commit that changes what needs to be changed, and finally, force a push.

2021-01-19 12:35 UTC, wlsf82 commented
@pedrohyvo, to avoid more going back and forth, I'll close this PR without merging it, and I'll create one myself and add you as a reviewer, ok?

2021-01-19 12:35 UTC, closed without merging